In [1]:

# tuple/array
# What is this?
#A tuple stays the same u cant change it
t = (1, 2 ,3)
# list/array
# What is this?
# Like a tuple but you can change it
l = [1, 2, 3]
print("t = ", t)
# l[0] = 5
# print(l)

t =  (1, 2, 3)


In [2]:
x = list(t)
x[1] = 4
print(x)

[1, 4, 3]


In [3]:
lst = []

In [4]:
x = list(t)
x[1] = 4
print(x)

[1, 4, 3]


In [7]:
# set
# What is this?
y = {1, 2, 3, 3}
print(y)
# dictionaries/map
# What is this?
# You can connect each value with a key to get it later
# key: value
d = {1: "hi", 3: "bye", "lol": 42}
print(d[1])
print(d["lol"])

{1, 2, 3}
hi
42


In [9]:
s = "string" # string, list of characters
b = False # bool
x = 1 # int
f = 1.0 # float (if you want to learn more, double vs float)
c = 's' # character, represented as number internally
print(s[2]) # 0 indexing
print(s[2:5]) # not inclusive of end

r
rin


In [10]:
f = 2
print(f) # 2

def f(): # f = function
    return 3
print(f) # 3, literally get whatever f is assigned to
print(f()) # 3, calling a function

2
<function f at 0x1074931a0>
3


In [1]:
# Higher order functions
def g(func): # g = function<func> -> func(8, 2)
    return func(8, 2)

def add(x, y):
    return x + y

def divide(x, y):
    return x / y

print(
    g(add)
)
print(
    g(divide)
)

10
4.0


In [6]:
# Return values
def f():
    print(3 + 2)
    return None

print(f())

def g():
    print(3 + 2)
    # No return value -> return None
print(g())
print(print(5))

def dont_do_anything_with_value():
    print(11)

print(11)
dont_do_anything_with_value()
x = dont_do_anything_with_value()

5
None
5
None
5
None
11
11


In [1]:
# python3 -m pip install numpy
import numpy as np

In [5]:
lst_five = list(range(5))
print(lst_five)
# 0, 1, 2, 3, 4
list_five_ones = [1,1,1,1,1]
print(list_five_ones)

print("STARTING np")
five = np.arange(5)
print(five)

# 0, 1, 2, 3, 4
five_ones = np.ones(5)
print(five_ones)
# 1 1 1 1 1
print(np.array(lst_five))

[0, 1, 2, 3, 4]
[1, 1, 1, 1, 1]
STARTING np
[0 1 2 3 4]
[1. 1. 1. 1. 1.]
[0 1 2 3 4]


In [7]:
# Typically np arrays are specific type, and array operations are faster because of this (meaning faster machine learning)
print(five.dtype)
print(five_ones.dtype)

int64
float64


In [20]:
# Regular python has pythonic way, numpy arrays math is doing element-wise math, like how normal math works
print(list_five_ones * 2) # regular python list
print(five_ones * 2) # numpy array

x = [2, 3] + [4, 5] + [52, 62, 66]
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[2. 2. 2. 2. 2.]
[2, 3, 4, 5, 52, 62, 66]


In [22]:
# List indexing/slicing, same between np and python
y = x[4]
print(y)
z = x[1:3]
print(z)
a = x[0:6:2]
print(a)

52
[3, 4]
[2, 4, 52]


In [24]:
x = [5, 10, 15,1234,13412424,3,7,468,59,5,3456356,568,5,245244567,35673,134,67,579,24566,88,765,226,65785,563,563,245,47579,9,8,77,367,4567,89776,23469,87655678,543,45689876543,456789,876543]
N = len(x)
# u = (x[0]+x[1]+x[2])/N
u = sum([x[i] for i in range(N)]) / N
print(u)
stdev = sum([(x[i]-u)**2 for i in range(N)])/N
print(stdev)

# plot the graph

1180545562.2564104
5.2135359348865204e+19
